import { getCharacters } from "@/api";
import Head from "next/head";
import { SetStateAction, useEffect, useState } from "react";
import { TCharater } from "../api/model";
import Image from "next/image"


export async function getStaticProps() {
  const res = await getCharacters()

  return {
    props: {
      charList : res.list
    }, 
  }
}


export default function Home(props: { charList: SetStateAction<TCharater[]>; } ) {
  const [list, setList] = useState<TCharater[]>([]);

  useEffect(() => {
    // getCharacters()
    //   .then((res) => setList(res.list))
    //   .catch(() => {});
    setList(props.charList)
  }, []);

  const characterList =
    list?.length &&
    list.map((i) => {
      return (
        <div key={i.id}>
          <Image src={i.image} alt={`${i.name} avatar`} width={150} height={150} />
        </div>
      );
    });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {characterList}
      </main>
    </>
  );
}